config/routes.rb
Rails.application.routes.draw do
  root to: 'boats#index'

  devise_for :users
  get 'bookings/history', to: 'bookings#history', as: :history

  resources :boats do
    resources :bookings, only: [:index, :new, :create]
  end

  resources :bookings, only: [:index, :new, :create] do
    resources :reviews, only: [:new, :create, :destroy]
  end


  get '/tagged', to: "boats#tagged", as: :tagged


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  mount_uploader :photo_1, PhotoUploader
  mount_uploader :photo_2, PhotoUploader
  mount_uploader :photo_3, PhotoUploader
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :description, :price, :title, presence: true, allow_blank: false
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  acts_as_taggable_on :tags
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :boat
  belongs_to :user
  has_one :review, dependent: :destroy
  validates :date_start, :date_end, presence: true
  # validate :end_must_be_after_start
  # validate :start_must_not_be_before_today

  # def end_must_be_after_start
  #   errors.add(:date_end, "must be after date start.") if date_start >= date_end
  # end

  # def start_must_not_be_before_today
  #   errors.add(:date_start, "should be at least today. Look ahead.") if date_start < Date.today
  # end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :rating, :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :boats
  has_many :bookings
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, presence: true, allow_blank: false

  validates_presence_of   :avatar
  validates_integrity_of  :avatar
  validates_processing_of :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password,
      :password_confirmation, :remember_me, :avatar, :avatar_cache, :remove_avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password,
      :password_confirmation, :current_password, :avatar, :avatar_cache, :remove_avatar])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_boat, only: [:show, :edit, :update, :destroy]

  def index
    @boats = policy_scope(Boat).order(created_at: :desc).limit(6).geocoded
    @markers = @boats.map do |boat|
      {
        lat: boat.latitude,
        lng: boat.longitude,
        infoWindow: render_to_string(partial: "/boats/info_window", locals: { boat: boat })
        # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }
    end
  end

  def new
    @boat = Boat.new
    authorize @boat
  end

  def create
    @boat = Boat.new(boat_params)
    @boat.user = current_user
    authorize @boat
    if @boat.save
      redirect_to @boat
    else
      render 'new'
    end
  end

  def tagged
    if params[:tag].present?
      @boats = Boat.tagged_with(params[:tag])
    else
      @boats = Boat.all
    end
    authorize @boats
  end

  def show
    @marker = [
      {lat: @boat.latitude,
      lng: @boat.longitude,
      infoWindow: render_to_string(partial: "/boats/info_window", locals: { boat: @boat })
      # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }]
    @related_boats = @boat.find_related_tags
  end

  def edit
  end

  def update
    @boat.user = current_user
    if @boat.update(boat_params)
      redirect_to @boat
    else
      render :edit
    end
  end

  def destroy
    @boat.destroy
    redirect_to boats_path
  end

  private

  def boat_params
    params.require(:boat).permit(:description, :price, :available, :title, :photo, :photo_1, :photo_2, :photo_3, :photo_cache, :address, tag_list: [])
  end

  def set_boat
    @boat = Boat.find(params[:id])
    authorize @boat
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @boats = policy_scope(Boat).where(user: current_user).order(created_at: :desc)
  end

  def new
    @booking = Booking.new
    authorize @booking
    @boat = Boat.find(params[:boat_id])
  end

  def create
    @booking = Booking.new(params_booking)
    @boat = Boat.find(params[:boat_id])
    @booking.user = current_user
    @booking.boat = @boat
    authorize @booking
    if @booking.save
      redirect_to '/bookings/history'
    else
      render 'new'
    end
  end

  def history
    @bookings = Booking.where(user: current_user)
    authorize @bookings
  end

  private

  def params_booking
    params.require(:booking).permit(:date_start, :date_end, :boat_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:new, :create]
  def index
  end

  def new
    @booking = Booking.find(params[:booking_id])
    authorize @booking
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @booking.review = @review
    authorize @booking
    if @review.save
      redirect_to history_path
    else
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boats/_form.html.erb
<%= simple_for_for @boat do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :tag_list, as: :check_boxes, collection: ["Yatch", "Sailing", "Canoe", "Cruise", "Fishing Boat", "Speedy", "Family", "Romantic", "Engine-Power", "Men-Power"] %>
<%= f.submit %>

app/views/boats/_info_window.html.erb
<h2><%= link_to boat.title, boat_path(boat) %></h2>
<p><%= boat.address %></p>
<%= cl_image_tag(boat.photo, width: 150, height: 150, crop: :thumb, gravity: :face) %>

app/views/boats/edit.html.erb
<%= simple_form_for @boat do |f| -%>
<%= f.input :title %>
<%= f.input :description %>
<%= f.input :price %>
<%= f.input :address %>
<%= f.submit %>
<% end -%>

app/views/boats/index.html.erb
<!--
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1559075479-e8da6f6fc3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80);">
  <h1>Set sail on your next <strong>boating adventure</strong>!</h1>
</div> -->

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1559075479-e8da6f6fc3fb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1650&q=80);">
  <div class="d-flex justify-content-end">
    <h1 class="display-4 text-right">Set sail on your next <strong>boating adventure</strong>!</h1>
  </div>
</div>

<div class="bg-white main-container">
  <h2 class="display-5 text-center text-dark pt-4">Boats Available Today</h2>
  <div class="row mx-3 pb-2">
    <% @boats.each do |b| %>
      <div class="d-flex col-sm-6 col-xs-12 col-md-4 my-1">
    <!-- style="width: 90%; height: 80%" -->
        <div class="card shadow-sm p-2 mb-1 bg-white rounded">
          <img class="card-img-top" src="<%= b.photo.url %>">
          <h5 class="card-title text-dark pt-2 pb-0"><%= b.title %></h5>
          <span class="text-xs text-muted mt-0 pt-0"><%= b.address %></span>
          <ul class="list-inline">
            <% b.tag_list.each do |tag|%>
             <%= link_to tagged_path(tag: tag) do %>
                <button class="btn-tag"><%= tag %></button>
              <% end %>
            <% end %>
          </ul>
          <p class="card-text mt-0 pt-0">Price per Day: <%= number_to_currency(b.price, :unit => "$", precision: 0) %></p>
          <%= link_to 'Details', boat_path(b), class: "btn btn-light" %>
          <% b.available %>
          <% b.user_id %>
        </div>
      </div>
    <% end %>
  </div>
<div>
</div class="container">
  <div class="container pt-3 pb-3 border-top">
    <div class="round"
      id="map"
      style="width: 100%;
      height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>
  </div>
</div>

<footer class="footer border border-top-dark">

  <div class="footer-copyright">
    Copyright boatnb 2019
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</footer>

app/views/boats/new.html.erb
<div class="layout-newboat-form-page">
  <div class="intro">
    <h1>List Your Boat</h1>
    <h4>Boatnb lets you make money renting out your boat</h4>
  </div>
  <div class="row">
    <div class="col-xs-12 col-sm-6 offset-sm-3">
      <div class="boat-form">
        <%= simple_form_for @boat do |f| -%>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :address %>
        <%= f.input :tag_list, as: :check_boxes, collection: ["Yacht", "Sailing", "2-person", "4-person", "Cruise", "Fishing Boat", "Speedy", "Family", "Romantic", "Engine-Power", "Men-Power"] %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :photo_1 %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :photo_2 %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.input :photo_3 %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.button :submit, "Create", class:"btn btn-create-account" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/boats/show.html.erb
<div class="img-container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),url(<%= @boat.photo.url%>)">
  </div>
  <div class="d-flex bg-white justify-content-between" style="position:absolute; bottom:0px; height:100px; left:0px; right:0px">
    <div class="d-flex align-self-center pl-3">
      <div>
        <h4 class="text-secondary font-weight-bold"><%= @boat.title %></h4>
        <h6 class="text-secondary text-muted"><%= @boat.description %></h6>
      </div>
    </div>
    <div class="d-flex flex-row align-items-center">
      <h6 id="price" class="text-secondary mr-4 align-middle"><%= number_to_currency(@boat.price, :unit => "$", precision: 0)%> / day</h6>
      <div class="d-flex flex-row mr-4 align-items-center">
        <% if policy(@boat).update? %>
          <%= link_to 'Edit', edit_boat_path(@boat), class:"btn btn-link btn-sm rounded align-top"%>
          <%= link_to 'Delete', boat_path(@boat), method: 'delete', data: { confirm: 'Are you sure you want to delete this boat?'}, class:"btn btn-link btn-sm rounded align-top"%>
        <% else %>
          <%= link_to 'Book Now', new_boat_booking_path(@boat), class:"btn btn-secondary rounded"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="d-flex bg-white mt-4">
  <div class="col-lg-6 col-md-6 col-s-12" style="height: 590px">
    <div class="card w-100" style="height: 175px">
      <div class="card-body rounded">
        <h5 class="card-title">Additional Boat Details</h5>
        <h6 class="card-subtitle text-muted mb-1">Shanghai, China</h6>
        <div class="d-flex flex-row">
        <% @boat.tag_list.each do |tag| %>
          <span class="border p-1 m-1 font-italic" style="font-size: 12px"><%= link_to tag, tagged_path(tag: tag) %></span>
        <% end %>
        </div>
        <p class="card-text font-italic mt-1">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.</p>
      </div>
    </div>
    <div id="carouselExampleIndicators" class="carousel slide flex-shrink-1" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner rounded">
        <div class="carousel-item active">
          <%= cl_image_tag(@boat.photo_1, class: "img-center w-100 rounded") %>
          <!-- <img class="d-block w-100" src="cl_image_tag(@boat.url)" alt="No Photo :/"> -->
        </div>
        <div class="carousel-item">
          <%= cl_image_tag(@boat.photo_2, class: "img-center w-100 rounded") %>
          <!-- <img class="d-block w-100" src=cl_image_tag("@boat.photo_1") alt="No Photo :/"> -->
        </div>
        <div class="carousel-item">
          <%= cl_image_tag(@boat.photo_3, class: "img-center w-100 rounded") %>
          <!-- <img class="d-block w-100" src="<%= cl_image_tag(@boat.photo_1) %>" alt="No Photo :/"> -->
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>

  <div class="col-lg-6 col-md-6 col-s-12" style="height: 590px">
    <div class="card w-100" style="height: 175px">
      <div class="card-body rounded">
        <h6 class="">Other Boats Similar to This One</h6>
        <div class="d-flex flex-row">
          <% @related_boats.each do |r| %>
            <a href="<%= boat_path(r) %>"><img class="img-thumbnail mx-1" src="<%= r.photo.url %>" width="175" height="175"></a>
          <% end %>
        </div>
      </div>
    </div>
    <div class="flex-shrink-1">
      <div
          id="map";
          style="width: 100%;
          height: 400px;"
          data-markers="<%= @marker.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
      </div>
    </div>
  </div>


<footer class="footer border border-top-dark">
  <div class="footer-copyright">
    Copyright BoatnB 2019
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-facebook pr-2 pl-2"></i></a>
    <a href="#"><i class="fab fa-instagram pr-2 pl-2"></i></a>
    <a href="#"><i class="fab fa-twitter pr-2 pl-2"></i></a>
  </div>
</footer>

app/views/boats/tagged.html.erb
<div class="booking-page">
  <div class="tag-card-category">
  </div>
  <div class="container justify-content-center">
    <h4 class="booking-subtitle">You are searching for: <%= params[:tag] %> tag</h4>
    <h5 style="color:black">Available boats:</h5>

    <% @boats.each do |boat| %>
    <div class="d-flex justify-content-left py-4">
      <%= cl_image_tag(boat.photo, class: 'tag-boat-picture') %>
      <div class="boat-tag-pic">
        <div class="boat-tag-title">
          <%= link_to boat.title, boat_path(boat), class: "title-boat" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/history.html.erb
<div class="booking-page">
  <div class="card-category">
    <h1 class="booking-title" style="margin-top: 24px;">Reservation Center</h1>
  </div>

  <div class="container justify-content-center">
    <h4 class="booking-subtitle">Upcoming reservations</h4>

    <% @bookings.each do |b| %>
      <% if b.date_end >= Date.today %>
        <div class="d-flex justify-content-left py-4">
          <img class="booking-card-img" src="<%= b.boat.photo %>" alt="Card image cap">
          <div class="d-flex">
            <div class="boat-title-b">
              <p class="booking-boat-title" style="font-weight: bold"><%= link_to b.boat.title, boat_path(b.boat_id) %></p>
              <p>Starting date: <%= b.date_start.strftime("%A %B %e %Y") %></p>
              <p>Returning date: <%=b.date_end.strftime("%A %B %e %Y") %></p>
              <p>Renting days: <%= day = (Date.parse(b.date_end.to_s) - Date.parse(b.date_start.to_s)).round %></p>
            </div>
            <div class="boat-owner-b" style="text-align: center">
                <p>Owner: <%=b.boat.user.first_name%> <%=b.boat.user.last_name %></p>
              <img src="<%= b.boat.user.avatar.url(:bright_face) %>" class="avatar-booking">
            </div>
            <div class="boat-price-b" style="text-align: center">
                <p style="font-weight: bold"> Full Price: </p>
                <p><%= number_to_currency(b.boat.price*day, :unit => "$") %> </p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>


    <h4 class="booking-subtitle"> Past Reservations</h4>

    <% @bookings.each do |b| %>
    <% if b.date_end < Date.today %>

      <div class="d-flex justify-content-left py-4">
        <img class="booking-card-img" src="<%= b.boat.photo %>" alt="Card image cap">
        <div class="d-flex">
          <div class="boat-title-b">
            <p class="booking-boat-title" style="font-weight: bold"><%= link_to b.boat.title, boat_path(b.boat_id) %></p>
            <p>Starting date: <%= b.date_start.strftime("%A %B %e %Y") %></p>
            <p>Returning date: <%=b.date_end.strftime("%A %B %e %Y") %></p>
            <p>Renting days: <%= day = (Date.parse(b.date_end.to_s) - Date.parse(b.date_start.to_s)).round %></p>
          </div>
            <div class="boat-owner-b" style="text-align: center">
              <p>Owner: <%=b.boat.user.first_name%> <%=b.boat.user.last_name %></p>
              <img src="<%= b.boat.user.avatar.url(:bright_face) %>" class="avatar-booking">
            </div>
            <div class="boat-price-b" style="text-align: center">
              <p style="font-weight: bold"> Full Price: </p>
              <p><%= number_to_currency(b.boat.price*day, :unit => "$") %> </p>
            </div>
        </div>
      </div>
            <div>
              <%= link_to "Rate your experience", new_booking_review_path(b) %>
              <% if b.review %>
                <%= b.review.rating %> <%= b.review.content %>
              <% end %>
            </div>
    <% end %>


    <% end %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="booking-page">
  <div class="card-category">
    <h1 class="booking-title" style="margin-top: 24px;">My Boats Center</h1>
  </div>

  <div class="container justify-content-center">

    <h4 class="booking-subtitle">My Boats</h4>

    <% @boats.each do |boat| %>
    <div class="d-flex justify-content-left py-4">
      <img class="booking-card-img" src="<%= boat.photo %>" alt="Card image cap">
      <div class="d-flex">
        <div class="boat-title-b">
          <p class="booking-boat-title" style="font-weight: bold"><%= link_to boat.title, boat_path(boat), class: "title-boat" %> </p>
        </div>
          <% d = 0 %>
          <% u = 0 %>
          <% m = 0 %>
        <div class="boat-owner-b" style="text-align: center">
          <% boat.bookings.each do |b| %>
          <% if b.date_end < Date.today %>
          <% u += 1 %>
          <% d += ((Date.parse(b.date_end.to_s) - Date.parse(b.date_start.to_s)).round) %>
          <% m += ((Date.parse(b.date_end.to_s) - Date.parse(b.date_start.to_s)).round)*(b.boat.price) %>
          <% end %>
        <% end %>
          <p> Rented to: <span style="font-size: 24px; color: darkgray;"><%= u %></span> users </p>
          <p> Rented for: <span style="font-size: 24px; color: darkgray;"><%= d %></span> days </p>
          <p> Earned: <span style="font-size: 24px; color: green;">  $ <%= m %></span>  </p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="layout-book-boat">
  <div class="intro">
    <h1>Request Boat Booking</h1>
  </div>
  <div class="row">
    <div class="col-xs-9 col-sm-4 offset-sm-4">
      <div class="boat-form">
        <%= simple_form_for [@boat, @booking] do |f| %>
        <%= f.input :date_start, discard_hour: true %>
        <%= f.input :date_end, discard_hour: true %>
        <%= f.button :submit, "Create Booking", class:"btn btn-create-account" %>
        <% end -%>
      </div>
    </div>
  </div>
</div>


<!-- ----------------------------------------------------------------------------------- -->


<!-- -------------------------------------------------------------------------------- -->

<!-- <div class="container" style="width: 40%">
   <form class="form pt-5">
    <div class="form-group">
      <label for="name">Renter First Name:</label>
      <input type="name" class="form-control" id="first name" placeholder="First Name">
    </div>
    <div class="form-group">
      <label for="name">Renter Last Name:</label>
      <input type="name" class="form-control" id="first name" placeholder="Last Name">
    </div>
    <div class="form-group">
      <label for="pwd">Requested Start Date:</label>
      <input class="form-control" type="date" value="2019/01/08" id="example-date-input">
    </div>
    <div class="form-group">
      <label for="pwd">Requested End Date:</label>
      <input class="form-control" type="date" value="2019/05/08" id="example-date-input">
    </div>
    <div class="form-group">
      <label for="abt">Booking Details:</label>
      <div>
        <textarea class="form-control" id="message" name="message" placeholder="Please tell the owner a little bit about yourselfand your boating plans..." rows="3"></textarea>
      </div>
    </div>
    <div class="text-center">
      <button type="submit" class="btn btn-secondary btn-md">
      Request Booking</button>
    </div>
  </form>
</div>
<div class="footer border border-top-dark mt-5">
  <div class="footer-copyright">
    Copyright BoatnB 2019
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-facebook pr-2 pl-2"></i></a>
    <a href="#"><i class="fab fa-instagram pr-2 pl-2"></i></a>
    <a href="#"><i class="fab fa-twitter pr-2 pl-2"></i></a>
  </div>
</div> -->

app/views/bookings/testing.html.erb
<%= link_to boat.title, boat_path(boat) %>
<%= cl_image_tag(boat.photo), class: 'some-class' %>


<img class="booking-card-img" src="<%= cl_image_tag(boat.photo, width: 150, height: 150, crop: :thumb, gravity: :face) %>">


<div class="card-category">
    <p class="booking-title" style="margin-top: 24px;"> All the <%= params[:tag] %> Boats as follows: </p>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Boatnb</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
      <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>

app/views/reviews/show.html.erb
<p>finaly</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://cdn4.iconfinder.com/data/icons/transportation-2-front-view/80/Transportation_front_view-11-512.png" %>
    <% end %>
    <ul class="nav">
    <% if user_signed_in? %>
      <li class="nav-item" style="align-self: center;">
          <%= link_to "Rent Out Your Boat", new_boat_path, class: "nav-link" %>
      </li>
      <li class="nav-item" style="align-self: center; padding-right: 8px;">
         Welcome, <%= current_user.first_name %>
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= current_user.avatar.url(:bright_face) %>"/>
        <div class="dropdown-menu dropdown-menu-right text-right text-muted pr-3 pb-3" aria-labelledby="navbarDropdown" style="width: 6rem;">
          <a class="dropdown-item" href="#"><%= link_to "My Boats", bookings_path %></a>
          <a class="dropdown-item" href="#"><%= link_to "My Bookings", history_path %></a>
          <a class="dropdown-item" href="#"><%= link_to "Log Out", destroy_user_session_path, method: :delete%></a>
        </div>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Rent Your Boat", new_boat_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
    </div>
</div>